//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controller/CharacterSwitch.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterSwitch : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterSwitch()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterSwitch"",
    ""maps"": [
        {
            ""name"": ""SwitchMesh"",
            ""id"": ""4e533668-ad65-4545-91e2-011521dac08a"",
            ""actions"": [
                {
                    ""name"": ""SwitchRight"",
                    ""type"": ""Button"",
                    ""id"": ""70254e37-6948-4698-822e-072c6820dfa7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4372a863-671f-4672-859f-012b8cd3349b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointClick"",
                    ""type"": ""Button"",
                    ""id"": ""b14923b3-0df8-4cc4-b4d5-dd56b63b7a6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""13b35757-3fb6-41a6-a48d-7932c2665ff4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c67a252-89f4-40ae-82ae-89c1373c2a48"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6c71311-d430-4007-aee9-a2619f741e6b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OpenSkinMenu"",
            ""id"": ""6d33de7c-b2df-4094-a500-76ce07e25715"",
            ""actions"": [
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""288d9e1f-9a25-498a-944f-8ea0ec1bc7b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""23d0eded-1ea1-43ca-8afa-208befc1c174"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SwitchMesh
        m_SwitchMesh = asset.FindActionMap("SwitchMesh", throwIfNotFound: true);
        m_SwitchMesh_SwitchRight = m_SwitchMesh.FindAction("SwitchRight", throwIfNotFound: true);
        m_SwitchMesh_SwitchLeft = m_SwitchMesh.FindAction("SwitchLeft", throwIfNotFound: true);
        m_SwitchMesh_PointClick = m_SwitchMesh.FindAction("PointClick", throwIfNotFound: true);
        // OpenSkinMenu
        m_OpenSkinMenu = asset.FindActionMap("OpenSkinMenu", throwIfNotFound: true);
        m_OpenSkinMenu_OpenMenu = m_OpenSkinMenu.FindAction("OpenMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SwitchMesh
    private readonly InputActionMap m_SwitchMesh;
    private ISwitchMeshActions m_SwitchMeshActionsCallbackInterface;
    private readonly InputAction m_SwitchMesh_SwitchRight;
    private readonly InputAction m_SwitchMesh_SwitchLeft;
    private readonly InputAction m_SwitchMesh_PointClick;
    public struct SwitchMeshActions
    {
        private @CharacterSwitch m_Wrapper;
        public SwitchMeshActions(@CharacterSwitch wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchRight => m_Wrapper.m_SwitchMesh_SwitchRight;
        public InputAction @SwitchLeft => m_Wrapper.m_SwitchMesh_SwitchLeft;
        public InputAction @PointClick => m_Wrapper.m_SwitchMesh_PointClick;
        public InputActionMap Get() { return m_Wrapper.m_SwitchMesh; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwitchMeshActions set) { return set.Get(); }
        public void SetCallbacks(ISwitchMeshActions instance)
        {
            if (m_Wrapper.m_SwitchMeshActionsCallbackInterface != null)
            {
                @SwitchRight.started -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnSwitchRight;
                @SwitchRight.performed -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnSwitchRight;
                @SwitchRight.canceled -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnSwitchRight;
                @SwitchLeft.started -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnSwitchLeft;
                @SwitchLeft.performed -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnSwitchLeft;
                @SwitchLeft.canceled -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnSwitchLeft;
                @PointClick.started -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnPointClick;
                @PointClick.performed -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnPointClick;
                @PointClick.canceled -= m_Wrapper.m_SwitchMeshActionsCallbackInterface.OnPointClick;
            }
            m_Wrapper.m_SwitchMeshActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SwitchRight.started += instance.OnSwitchRight;
                @SwitchRight.performed += instance.OnSwitchRight;
                @SwitchRight.canceled += instance.OnSwitchRight;
                @SwitchLeft.started += instance.OnSwitchLeft;
                @SwitchLeft.performed += instance.OnSwitchLeft;
                @SwitchLeft.canceled += instance.OnSwitchLeft;
                @PointClick.started += instance.OnPointClick;
                @PointClick.performed += instance.OnPointClick;
                @PointClick.canceled += instance.OnPointClick;
            }
        }
    }
    public SwitchMeshActions @SwitchMesh => new SwitchMeshActions(this);

    // OpenSkinMenu
    private readonly InputActionMap m_OpenSkinMenu;
    private IOpenSkinMenuActions m_OpenSkinMenuActionsCallbackInterface;
    private readonly InputAction m_OpenSkinMenu_OpenMenu;
    public struct OpenSkinMenuActions
    {
        private @CharacterSwitch m_Wrapper;
        public OpenSkinMenuActions(@CharacterSwitch wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenMenu => m_Wrapper.m_OpenSkinMenu_OpenMenu;
        public InputActionMap Get() { return m_Wrapper.m_OpenSkinMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OpenSkinMenuActions set) { return set.Get(); }
        public void SetCallbacks(IOpenSkinMenuActions instance)
        {
            if (m_Wrapper.m_OpenSkinMenuActionsCallbackInterface != null)
            {
                @OpenMenu.started -= m_Wrapper.m_OpenSkinMenuActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.performed -= m_Wrapper.m_OpenSkinMenuActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.canceled -= m_Wrapper.m_OpenSkinMenuActionsCallbackInterface.OnOpenMenu;
            }
            m_Wrapper.m_OpenSkinMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenMenu.started += instance.OnOpenMenu;
                @OpenMenu.performed += instance.OnOpenMenu;
                @OpenMenu.canceled += instance.OnOpenMenu;
            }
        }
    }
    public OpenSkinMenuActions @OpenSkinMenu => new OpenSkinMenuActions(this);
    public interface ISwitchMeshActions
    {
        void OnSwitchRight(InputAction.CallbackContext context);
        void OnSwitchLeft(InputAction.CallbackContext context);
        void OnPointClick(InputAction.CallbackContext context);
    }
    public interface IOpenSkinMenuActions
    {
        void OnOpenMenu(InputAction.CallbackContext context);
    }
}
