//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controller/GameResetter.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameResetter : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameResetter()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameResetter"",
    ""maps"": [
        {
            ""name"": ""ResetGame"",
            ""id"": ""58ea4d41-c0ff-4cfa-9f49-19e339df795e"",
            ""actions"": [
                {
                    ""name"": ""ResetGameplay"",
                    ""type"": ""Button"",
                    ""id"": ""1bd23045-ced6-4ce4-92c5-76feb1ff16a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""88e1c0ff-299b-490f-b51c-624d00b42f94"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetGameplay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ResetGame
        m_ResetGame = asset.FindActionMap("ResetGame", throwIfNotFound: true);
        m_ResetGame_ResetGameplay = m_ResetGame.FindAction("ResetGameplay", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ResetGame
    private readonly InputActionMap m_ResetGame;
    private IResetGameActions m_ResetGameActionsCallbackInterface;
    private readonly InputAction m_ResetGame_ResetGameplay;
    public struct ResetGameActions
    {
        private @GameResetter m_Wrapper;
        public ResetGameActions(@GameResetter wrapper) { m_Wrapper = wrapper; }
        public InputAction @ResetGameplay => m_Wrapper.m_ResetGame_ResetGameplay;
        public InputActionMap Get() { return m_Wrapper.m_ResetGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ResetGameActions set) { return set.Get(); }
        public void SetCallbacks(IResetGameActions instance)
        {
            if (m_Wrapper.m_ResetGameActionsCallbackInterface != null)
            {
                @ResetGameplay.started -= m_Wrapper.m_ResetGameActionsCallbackInterface.OnResetGameplay;
                @ResetGameplay.performed -= m_Wrapper.m_ResetGameActionsCallbackInterface.OnResetGameplay;
                @ResetGameplay.canceled -= m_Wrapper.m_ResetGameActionsCallbackInterface.OnResetGameplay;
            }
            m_Wrapper.m_ResetGameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ResetGameplay.started += instance.OnResetGameplay;
                @ResetGameplay.performed += instance.OnResetGameplay;
                @ResetGameplay.canceled += instance.OnResetGameplay;
            }
        }
    }
    public ResetGameActions @ResetGame => new ResetGameActions(this);
    public interface IResetGameActions
    {
        void OnResetGameplay(InputAction.CallbackContext context);
    }
}
