//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controller/OpenSkinMenu.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @OpenSkinMenu : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @OpenSkinMenu()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""OpenSkinMenu"",
    ""maps"": [
        {
            ""name"": ""SkinMenu"",
            ""id"": ""c733e180-6220-40d6-abae-aca6fb5a9a6b"",
            ""actions"": [
                {
                    ""name"": ""OpenSkinMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6ef1fd31-df6f-47d3-94e6-0e37ada52505"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f3bbe533-65d8-4595-bfd9-b801d97dfa05"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSkinMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SkinMenu
        m_SkinMenu = asset.FindActionMap("SkinMenu", throwIfNotFound: true);
        m_SkinMenu_OpenSkinMenu = m_SkinMenu.FindAction("OpenSkinMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SkinMenu
    private readonly InputActionMap m_SkinMenu;
    private ISkinMenuActions m_SkinMenuActionsCallbackInterface;
    private readonly InputAction m_SkinMenu_OpenSkinMenu;
    public struct SkinMenuActions
    {
        private @OpenSkinMenu m_Wrapper;
        public SkinMenuActions(@OpenSkinMenu wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenSkinMenu => m_Wrapper.m_SkinMenu_OpenSkinMenu;
        public InputActionMap Get() { return m_Wrapper.m_SkinMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SkinMenuActions set) { return set.Get(); }
        public void SetCallbacks(ISkinMenuActions instance)
        {
            if (m_Wrapper.m_SkinMenuActionsCallbackInterface != null)
            {
                @OpenSkinMenu.started -= m_Wrapper.m_SkinMenuActionsCallbackInterface.OnOpenSkinMenu;
                @OpenSkinMenu.performed -= m_Wrapper.m_SkinMenuActionsCallbackInterface.OnOpenSkinMenu;
                @OpenSkinMenu.canceled -= m_Wrapper.m_SkinMenuActionsCallbackInterface.OnOpenSkinMenu;
            }
            m_Wrapper.m_SkinMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenSkinMenu.started += instance.OnOpenSkinMenu;
                @OpenSkinMenu.performed += instance.OnOpenSkinMenu;
                @OpenSkinMenu.canceled += instance.OnOpenSkinMenu;
            }
        }
    }
    public SkinMenuActions @SkinMenu => new SkinMenuActions(this);
    public interface ISkinMenuActions
    {
        void OnOpenSkinMenu(InputAction.CallbackContext context);
    }
}
